### ISSUE TITLE
Configure logging to go to stdout instead of a file with env

### ISSUE THREAD

**Issue by jonespm** [longhornopen/qualtrics-lti#2] opened 2021-12-20 16:28 UTC
I noticed that the log files get written to logs/laravel.logs  via this file
https://github.com/longhornopen/qualtrics-lti/blob/main/web/config/logging.php

I saw this guide that allows you to configure it to go to stdout
http://devlog.markhlavac.com/2019/06/05/laravel-logging-console-using-standard-output-stdout/

It would be more useful to us in our hosting environment if we could change an environment variable to adjust the logs to go to stdout instead of a file, rather than modify this logging.php. 

Is there already a setting for this or does this need to be slightly configured to work?

**Comment by chrispittman** [comment] 2021-12-20 18:07
It's confusingly named in Laravel, but the 'errorlog' driver sends output to stdout.  You can set a `LOG_CHANNEL=errorlog` env var to use it.  It's controlled by the stanza at https://github.com/longhornopen/qualtrics-lti/blob/6b767bff93251d40a5f1f997d11768e2d533457c/web/config/logging.php#L90-L93 - notice that you can also set LOG_LEVEL if you want.

**Comment by jonespm** [comment] 2021-12-20 18:28
Great, thanks, looks like that works.

I had the LTI key mistyped, it was giving a 500 error on launch and I wasn't sure what the error was.

**Comment by chrispittman** [comment] 2021-12-20 18:58
Sweet.  I'm assuming the rest of the problem is just a key/secret mismatch - you can check the `lti2_consumer` table to see the keys & secrets you're expecting.

Closing this particular issue, but feel free to reach out if we can help with anything.

**Closed by chrispittman** 2021-12-20 18:58 UTC
